//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePregledi_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LijekPregled
    {
        public int LijekId { get; set; }
        public int PregledId { get; set; }
        public string Uputstvo { get; set; }
    
        public virtual Lijek Lijek { get; set; }
        public virtual Pregled Pregled { get; set; }
    }
}
