//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePregledi_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ePreglediEntities : DbContext
    {
        public ePreglediEntities()
            : base("name=ePreglediEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alergija> Alergijas { get; set; }
        public virtual DbSet<Dijagnoza> Dijagnozas { get; set; }
        public virtual DbSet<DijagnozaPregled> DijagnozaPregleds { get; set; }
        public virtual DbSet<Doktor> Doktors { get; set; }
        public virtual DbSet<Drzava> Drzavas { get; set; }
        public virtual DbSet<Grad> Grads { get; set; }
        public virtual DbSet<KrvnaGrupa> KrvnaGrupas { get; set; }
        public virtual DbSet<Lijek> Lijeks { get; set; }
        public virtual DbSet<LoginPodaci> LoginPodacis { get; set; }
        public virtual DbSet<Osoba> Osobas { get; set; }
        public virtual DbSet<Pacijent> Pacijents { get; set; }
        public virtual DbSet<Pregled> Pregleds { get; set; }
        public virtual DbSet<LijekPregled> LijekPregleds { get; set; }
    }
}
