//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePregledi_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osoba
    {
        public int OsobaId { get; set; }
        public string JMBG { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<System.DateTime> DatumRodjenja { get; set; }
        public string Spol { get; set; }
        public string Email { get; set; }
        public string BrojTelefona { get; set; }
        public string Adresa { get; set; }
        public Nullable<int> GradId { get; set; }
        public Nullable<int> DrzavaId { get; set; }
        public string Token { get; set; }
        public string Slika { get; set; }
    
        public virtual Doktor Doktor { get; set; }
        public virtual Drzava Drzava { get; set; }
        public virtual Grad Grad { get; set; }
        public virtual LoginPodaci LoginPodaci { get; set; }
        public virtual Pacijent Pacijent { get; set; }
    }
}
